# **Problem Statement**:
The objective of this project is to develop a robust data preprocessing pipeline for real estate property listings. The pipeline should encompass both numerical and textual data, focusing on cleaning, transforming, and enriching the dataset to provide a foundation for accurate analysis and modeling.

# **Dataset Description**:

The dataset comprises the following columns:



* **property_name**: Name or title associated with the property listing.

* **property_type**: Type or category of the property (e.g., apartment, villa, penthouse).

* **society**: Name of the housing society or complex where the property is situated.

* **price**: Selling or listing price of the property.

* **price_per_sqft**: Price per square foot of the property.

* **area**: Estimated area of the property in square units.

* **areaWithType**: Combination of area and property type, providing size and type context.

* **bedRoom**: Number of bedrooms in the property.

* **bathroom**: Number of bathrooms in the property.

* **balcony**: Number of balconies attached to the property.

* **additionalRoom**: Count of extra rooms or spaces in the property.

* **address**: Location details of the property, including city and locality.

* **floorNum**: Floor number of the property within the building.

* **facing**: Direction the property is facing (e.g., north, south, east).

* **agePossession**: Age of the property or years since construction.

* **nearbyLocations**: Landmarks or neighborhoods near the property's location.

* **description**: Detailed description of property features and amenities.

* **furnishDetails**: Level of furnishing in the property (e.g., fully furnished, semi-furnished).

* **features**: Special amenities associated with the property (e.g., pool, security).

* **rating**: Rating or feedback score assigned to the property.



# **Data Preprocessing**:



* Handle missing values, correct data types, and remove duplicates.

* Calculate 'area' based on price and price per square foot.

* Encode categorical variables like property type and facing direction.

* and many more

and lastly Export Cleaned Data

# **Import Basic Libraries**

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('houses.csv')
df.head(3)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898

# **Basic Checks**

In [4]:
# shape
df.shape

(1036, 21)

In [5]:
# Check for missing values
df.isnull().sum()

property_name        0
link                 0
society            584
price               68
rate                38
area                 0
areaWithType        49
bedRoom             49
bathroom            49
balcony             49
additionalRoom     447
address              5
noOfFloor           69
facing             362
agePossession       49
nearbyLocations    123
description          0
furnishDetails     293
features           362
rating             129
property_id          0
dtype: int64

In [6]:
# Duplictes
df.duplicated().sum()

13

In [7]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1036 entries, 0 to 1035
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1036 non-null   object
 1   link             1036 non-null   object
 2   society          452 non-null    object
 3   price            968 non-null    object
 4   rate             998 non-null    object
 5   area             1036 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 170.1+ KB

# **Drop Unwanted Columns**

In [8]:
# Drop columns -> property_name,link,property_id

df.drop(columns=['link','property_id'],inplace=True)

In [9]:
df.head(3)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **Rename Some columns**

In [10]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)

In [11]:
df.head(3)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **Society**

In [12]:
df['society'].value_counts()

International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
Vipul Tatvam Villa                                   26
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             13
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      9
Uppal Southend4.0 ★                                   8
Not Applicable                                        7
Ansals Palam Vihar                                    6
Experion Windchants3.8 ★                              6
Sushant Lok 1 Builder Floors                          6
DLF City Phase 1                                      5
Vatika India Next4.1 ★                                4
nul                                                   4
DLF New Town Heights 24.0 ★                           4
Ansal Sushant Lok Plots4.1 ★                          4
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Vatika Signature Villas                               3
Palam Vihar Extension West Zone RWA                   3
DLF City Plots Phase 3                                3
SS Aaron Ville                                        3
Eros Rosewood Villas                                  3
Luxury DLF City Floors                                3
Housing Board Colony                                  3
Eros Rosewood City4.0 ★                               3
Malibu Towne                                          3
Central Park Flower Valley                            3
Anant Raj Estates                                     3
Tata Primanti4.1 ★                                    3
Unitech Nirvana Birch Court                           3
Rattan Garden                                         3
Puri Diplomatic Greens4.0 ★                           3
BPTP Astaire Gardens3.7 ★                             3
Sector 14 RWA                                         3
Ansals Florence Villa                                 3
Bhim Garh Kheri                                       2
Sobha City                                            2
Bestech Park View Ananda4.2 ★                         2
IFFCO Nagar and 17B RWA                               2
Ardee City3.8 ★                                       2
SS Hibiscus                                           2
Unitech Escape3.8 ★                                   2
Satya The Hermitage3.5 ★                              2
Hans Enclave                                          2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Project Mianwali Colony                               2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Silverglades Tarudhan Valley Golf Resort              2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
DLF New Town Heights3.7 ★                             2
Emaar Emerald Hills4.1 ★                              2
Suncity Essel Towers4.2 ★                             2
Ansal API Esencia3.7 ★                                2
Unitech Deerwood Chase                                2
Central Park Flower Valley Cerise Floors              1
Kothi                                                 1
Birla Navya                                           1
Om Nagar, Sector-11                                   1
HUDA Ashok Vihar Phase 13.9 ★                         1
Ansal API Spanish Court                               1
4S Aradhya Homes                                      1
Sector-17C                                            1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
private house                                         1
Ashok Vihar Phase 3 Gurgaon                           1
DLF City Plots Phase 4                                1
nirvana country                                       1
Landmark House                                        1
Farrukhnagar                                          1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Prem Kunj                                             1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
huda sector-56 gurgaon                                1
Satya The Legend3.8 ★                                 1
Huda Floor                                            1
Huda                                                  1
Grover Homes Sec 4                                    1
Sector 57 Huda                                        1
Saksham Welfare Association                           1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
DLF Pink Town House4.0 ★                              1
FLOOR WISE DESIGNER KOTHI                             1
sector 37                                             1
Adani Brahma Samsara4.2 ★                             1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
All Punjabi Welfare Association                       1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF South City 1                                      1
Ansal Sushant Residency                               1
DLF City Plot Phase 3                                 1
sneh vihar                                            1
DLF The Arbour                                        1
mian wali                                             1
Ansal Celebrity Homes                                 1
Laxmi Garden Sector-11                                1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Surat nagar phase 2                                   1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
ATS Tourmaline3.9 ★                                   1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
Bhawani enclave                                       1
DLF Garden City Floors                                1
Shri Shyam Residency                                  1
My Home                                               1
Sheetla Enclave                                       1
HUDA Plot Sector 38                                   1
Suncity Avenue 76                                     1
SS Omnia                                              1
secter 16a daultabad faridabad house no 313           1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
rajendra park sec 105                                 1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
Ansal Heights3.2 ★                                    1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
Ninex City                                            1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
Signature Global Park4.0 ★                            1
ROW HOUSE                                             1
Name: society, dtype: int64

In [13]:
df['society'].value_counts().shape

(185,)

In [14]:
import re
df['society']=df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [15]:
df['society'].value_counts().shape

(183,)

In [16]:
df['society']=df['society'].str.replace('nan','independent')

In [17]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
540,6 Bedroom House for sale in DLF Phase 2,independent,13 Crore,"₹ 45,710/sq.ft.",(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6 Bedrooms,8 Bathrooms,3+ Balconies,"Pooja Room,Servant Room,Study Room,Store Room","DLF Phase 2, Gurgaon, Haryana",NaN,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
169,4 Bedroom House for sale in Ashok Vihar Phase ...,ashok vihar phase 3 gurgaon,95 Lac,"₹ 8,878/sq.ft.",(99 sq.m.) Plot Area,Plot area 1070(99.41 sq.m.),4 Bedrooms,3 Bathrooms,2 Balconies,NaN,"House No 58 Gali No 11, Ashok Vihar Phase 3 Ex...",1 Floors,East,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",60 60 gaj ke 2 plot bna rkhe hai 2 side wala p...,NaN,['Park'],"['Environment3 out of 5', 'Lifestyle4 out of 5..."
738,12 Bedroom House for sale in DLF Phase 1,luxury dlf city floors,8.25 Crore,"₹ 45,833/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Servant Room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4 Floors,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
841,3 Bedroom House for sale in Nirvana Country,unitech aspen greens,12 Crore,"₹ 37,037/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,"Study Room,Servant Room","Nirvana Country, Gurgaon, Haryana",1 Floors,East,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Park feacing villa for sale in nirvana country...,"['3 Wardrobe', '3 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
328,2 Bedroom House for sale in Sector 13 Gurgaon,independent,1.5 Crore,"₹ 10,518/sq.ft.",(132 sq.m.) Plot Area,Plot area 1426(132.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,"Pooja Room,Study Room","Hno. 26, A Block, Sector 13 Gurgaon, Gurgaon, ...",3 Floors,South-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...","The house is located in sanjay gram, sector 13...",NaN,"['Water Storage', 'Waste Disposal']","['Environment4 out of 5', 'Lifestyle5 out of 5..."

# **Price**

In [18]:
df['price'].value_counts()

3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
8 Crore             13
5 Crore             13
4.5 Crore           13
50 Lac              13
70 Lac              13
75 Lac              13
85 Lac              12
2.5 Crore           12
8.5 Crore           12
7 Crore             12
4 Crore             11
1.5 Crore           11
60 Lac              10
45 Lac              10
Price on Request    10
90 Lac              10
10 Crore            10
9 Crore             10
2.25 Crore          10
80 Lac               9
1.7 Crore            9
9.5 Crore            9
1.1 Crore            9
12 Crore             9
2 Crore              9
1.6 Crore            8
4.6 Crore            8
1 Crore              8
6.75 Crore           8
11 Crore             8
3.75 Crore           8
1.2 Crore            7
2.1 Crore            7
1.3 Crore            7
65 Lac               7
95 Lac               7
55 Lac               7
40 Lac               7
1.35 Crore           7
12.5 Crore           7
1.45 Crore           6
2.95 Crore           6
7.5 Crore            6
5.7 Crore            6
4.25 Crore           6
3.25 Crore           6
13.5 Crore           6
5.6 Crore            6
2.75 Crore           6
6.25 Crore           6
1.15 Crore           6
7.25 Crore           6
10.5 Crore           6
16 Crore             6
3.6 Crore            6
35 Lac               5
5.75 Crore           5
4.75 Crore           5
15 Crore             5
2.8 Crore            5
3 Crore              5
17 Crore             5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
8.25 Crore           5
9.25 Crore           4
18 Crore             4
4.35 Crore           4
2.4 Crore            4
42 Lac               4
1.65 Crore           4
4.7 Crore            4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
13 Crore             4
8.4 Crore            4
6.8 Crore            4
11.5 Crore           4
3.2 Crore            4
5.8 Crore            4
3.3 Crore            4
62 Lac               3
7.2 Crore            3
49 Lac               3
3.85 Crore           3
4.45 Crore           3
82 Lac               3
3.55 Crore           3
1.16 Crore           3
2.3 Crore            3
1.9 Crore            3
34 Lac               3
1.55 Crore           3
20 Crore             3
2.2 Crore            3
3.1 Crore            3
5.65 Crore           3
2.9 Crore            3
1.95 Crore           3
5.15 Crore           3
92 Lac               3
6.4 Crore            3
1.85 Crore           3
2.55 Crore           3
4.3 Crore            3
7.35 Crore           3
19 Crore             3
6.95 Crore           3
3.4 Crore            3
32 Lac               3
4.95 Crore           2
58 Lac               2
58.25 Lac            2
14 Crore             2
2.15 Crore           2
9.9 Crore            2
89 Lac               2
1.05 Crore           2
3.51 Crore           2
3.15 Crore           2
3.35 Crore           2
8.49 Crore           2
10.85 Crore          2
5.4 Crore            2
11.95 Crore          2
36 Lac               2
3.65 Crore           2
26 Crore             2
10.55 Crore          2
3.05 Crore           2
7.1 Crore            2
6.3 Crore            2
11.25 Crore          2
15.5 Crore           2
48 Lac               2
11.75 Crore          2
67 Lac               2
19.5 Crore           2
10.45 Crore          2
1.75 Crore           2
7.99 Crore           2
30 Lac               2
66 Lac               2
10.3 Crore           1
2.47 Crore           1
3.7 Crore            1
7.3 Crore            1
4.15 Crore           1
18.4 Crore           1
22 Crore             1
6.15 Crore           1
4.4 Crore            1
8.45 Crore           1
46.75 Lac            1
9.4 Crore            1
18.5 Crore           1
12.25 Crore          1
27.5 Crore           1
52.75 Lac            1
5.88 Crore           1
8.31 Crore           1
6.21 Crore           1
2.01 Crore           1
3.9 Crore            1
5.1 Crore            1
1.83 Crore           1
99 Lac               1
2.45 Crore           1
2.65 Crore           1
1.18 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
15.1 Crore           1
9.85 Crore           1
1.27 Crore           1
1.04 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
8.9 Crore            1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
4.49 Crore           1
65.8 Lac             1
8.81 Crore           1
55.11 Lac            1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
5.46 Crore           1
52 Lac               1
10.56 Crore          1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
3.12 Crore           1
7.49 Crore           1
6.81 Crore           1
22 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
6.6 Crore            1
5.35 Crore           1
5.85 Crore           1
5.9 Crore            1
6.2 Crore            1
3.93 Crore           1
8.7 Crore            1
7.69 Crore           1
15.5 Lac             1
8.8 Crore            1
4.12 Crore           1
1.87 Crore           1
12.39 Crore          1
7.6 Crore            1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
61 Lac               1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
18.02 Crore          1
10.75 Crore          1
96 Lac               1
24 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
44 Lac               1
13 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
2.98 Crore           1
Name: price, dtype: int64

In [19]:
df['price'].value_counts().shape

(302,)

In [20]:
df = df[df['price'] != 'Price on Request']

In [21]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [22]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [23]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

<ipython-input-23-45c08249b2fd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].str.split(' ').apply(treat_price)

In [24]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **price_per_sqft**

In [25]:
df['price_per_sqft'].value_counts()

₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     11
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 26,667/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 9,444/sq.ft.       5
₹ 23,333/sq.ft.      5
₹ 5,000/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 11,100/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 13,333/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 7,058/sq.ft.       4
₹ 21,605/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 24,691/sq.ft.      4
₹ 35,000/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 16,058/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 6,944/sq.ft.       3
₹ 17,284/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 25,562/sq.ft.      3
₹ 24,500/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 20,000/sq.ft.      3
₹ 60,000/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 25,000/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 25,926/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 33,951/sq.ft.      3
₹ 15,555/sq.ft.      3
₹ 32,222/sq.ft.      3
₹ 13,889/sq.ft.      3
₹ 45,833/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 50,000/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 8,888/sq.ft.       2
₹ 26,389/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 29,630/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 100,000/sq.ft.     2
₹ 12,963/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 6,666/sq.ft.       2
₹ 7,407/sq.ft.       2
₹ 35,185/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 13,000/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 20,833/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 12,342/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 7,500/sq.ft.       2
₹ 11,852/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 24,306/sq.ft.      2
₹ 17,037/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 44,444/sq.ft.      2
₹ 17,778/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 29,716/sq.ft.      2
₹ 21,000/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 27,971/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 12,519/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 37,777/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 16,378/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 20,690/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 20,988/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 400,000/sq.ft.     1
₹ 24,455/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 33,592/sq.ft.      1
₹ 21,296/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 42,054/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 24,171/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 22,812/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 27,461/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 8,127/sq.ft.       1
₹ 7,555/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 24,074/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 7,777/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 12,551/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 28,787/sq.ft.      1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 20,026/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 47,803/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 25,463/sq.ft.      1
₹ 15,926/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 20,566/sq.ft.      1
₹ 5,128/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 15,444/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 16,600/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 18,088/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 29,333/sq.ft.      1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 40,741/sq.ft.      1
₹ 21,786/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 14,667/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 40,850/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 17,187/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 6,849/sq.ft.       1
₹ 34,037/sq.ft.      1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 10,579/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 26,063/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 26,502/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 15,111/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 28,233/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 14,184/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 4,260/sq.ft.       1
₹ 20,115/sq.ft.      1
₹ 8,101/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 8,486/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 2,296/sq.ft.       1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 8,411/sq.ft.       1
₹ 41,666/sq.ft.      1
₹ 4,808/sq.ft.       1
₹ 7,280/sq.ft.       1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 6,173/sq.ft.       1
₹ 2/sq.ft.           1
₹ 5,472/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 57,692/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 8,007/sq.ft.       1
₹ 8,928/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 13,542/sq.ft.      1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 28,490/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 4,074/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 21,250/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 9,654/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 17,500/sq.ft.      1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 4,000/sq.ft.       1
₹ 7,820/sq.ft.       1
₹ 13,499/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 16,892/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 14,323/sq.ft.      1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 6,981/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 3,519/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 5,583/sq.ft.       1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 11,904/sq.ft.      1
₹ 245,398/sq.ft.     1
₹ 6,707/sq.ft.       1
₹ 6,481/sq.ft.       1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 24,305/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 14,072/sq.ft.      1
₹ 21,111/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 10,784/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 232/sq.ft.         1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 218,750/sq.ft.     1
₹ 11,556/sq.ft.      1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 10,378/sq.ft.      1
₹ 7,576/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 151/sq.ft.         1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 25,103/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 33,129/sq.ft.      1
Name: price_per_sqft, dtype: int64

In [26]:
df['price_per_sqft'].value_counts().shape

(750,)

In [27]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [28]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **bedRoom**

In [30]:
df['bedRoom'].value_counts()

4 Bedrooms     239
5 Bedrooms     195
3 Bedrooms     148
2 Bedrooms      88
6 Bedrooms      82
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      34
7 Bedrooms      31
12 Bedrooms     29
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: bedRoom, dtype: int64

In [34]:
df['bedRoom'].isnull().sum()

49

In [35]:
df = df[~df['bedRoom'].isnull()]

In [36]:
df.shape

(977, 19)

In [ ]:
df['bedRoom']= df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [38]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **bathroom**

In [39]:
df['bathroom'].value_counts()

4 Bathrooms     233
3 Bathrooms     166
5 Bathrooms     139
2 Bathrooms     114
6 Bathrooms      85
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      29
12 Bathrooms     23
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: bathroom, dtype: int64

In [40]:
df['bathroom'].isnull().sum()

0

In [ ]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [42]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **balcony**

In [43]:
df['balcony'].value_counts()

3+ Balconies    373
2 Balconies     223
3 Balconies     161
No Balcony      115
1 Balcony       105
Name: balcony, dtype: int64

In [44]:
df['balcony'].isnull().sum()

0

In [ ]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('NO','0')

In [46]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **additionalRoom**

In [47]:
df['additionalRoom'].value_counts()

Servant Room                                     82
Pooja Room,Study Room,Servant Room,Store Room    63
Others                                           59
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               34
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Pooja Room,Store Room,Study Room,Servant Room     9
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Servant Room,Store Room                7
Study Room,Servant Room,Pooja Room,Store Room     7
Servant Room,Pooja Room,Store Room                7
Store Room,Servant Room                           6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Servant Room,Store Room,Pooja Room                5
Study Room,Pooja Room,Servant Room                5
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Servant Room,Study Room,Store Room,Pooja Room     2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: additionalRoom, dtype: int64

In [48]:
df['additionalRoom'].isnull().sum()

388

In [ ]:
df['additionalRoom'].fillna('not available',inplace=True)

In [ ]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [54]:
df['additionalRoom'].isnull().sum()

0

In [55]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **noOfFloor**

In [56]:
df['noOfFloor'].value_counts()

3 Floors     309
2 Floors     294
1 Floors     181
4 Floors     137
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: noOfFloor, dtype: int64

In [57]:
df['noOfFloor'].isnull().sum()

20

In [ ]:
df['noOfFloor']=df['noOfFloor'].str.split().str.get(0)

In [59]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [ ]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [65]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **facing**

In [66]:
df['facing'].value_counts()

East          181
North-East    159
North         113
West           75
North-West     44
South-East     40
South          36
South-West     25
Name: facing, dtype: int64

In [68]:
df['facing'].isnull().sum()

304

In [ ]:
df['facing'].fillna('NA',inplace=True)

In [70]:
df['facing'].isnull().sum()

0

In [72]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# **area**

In [ ]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [74]:
df.insert(loc=1,column='property_type',value='house')

In [75]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [77]:
df.shape

(977, 20)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 977 entries, 0 to 1035
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    977 non-null    object
 1   property_type    977 non-null    object
 2   society          977 non-null    object
 3   price            958 non-null    float64
 4   price_per_sqft   958 non-null    float64
 5   area             958 non-null    float64
 6   areaWithType     977 non-null    object
 7   bedRoom          977 non-null    int64
 8   bathroom         977 non-null    int64
 9   balcony          977 non-null    object
 10  additionalRoom   977 non-null    object
 11  address          972 non-null    object
 12  floorNum         957 non-null    object
 13  facing           977 non-null    object
 14  agePossession    977 non-null    object
 15  nearbyLocations  861 non-null    object
 16  description      977 non-null    object
 17  furnishDetails   740 non-null    object
 18  features         674 non-null    object
 19  rating           856 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 160.3+ KB

In [79]:
df.to_csv('houses_cleaned.csv',index=False)